version: "3.9"

networks:
  guacnetwork_compose:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw


  # postgres 
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    networks:
      guacnetwork_compose:
    environment:
      TZ: Asia/Shanghai
      PGDATA: /var/lib/postgresql/data/guacamole
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=md5
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      TZ: Asia/Shanghai
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    links:
      - "guacd"
      - "postgres"
    ports:
      - "8080:8080"
    networks:
      guacnetwork_compose:


######init postgres#######
#docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
#docker cp initdb.sql postgres:/
#docker exec -it postgres bash

##in container postgres.##
#su postgres
#createdb guacamole_db
#cat initdb.sql | psql -d guacamole_db -f -



######Verifying the Guacamole install####
#http://HOSTNAME:8080/guacamole/
#username:guacadmin
#password:guacadmin
