version: "3.9"


services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always
    ports:
    - "4822:4822"
    environment:
      TZ: Asia/Shanghai


  # postgres 
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      TZ: Asia/Shanghai
      #PGDATA: /var/lib/postgresql/data/guacamole
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=md5
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
    - ./data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      TZ: Asia/Shanghai
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    links:
      - "guacd"
      - "postgres"
    ports:
      - "8080:8080"
    restart: always

######init postgres#######
#docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
#docker cp initdb.sql postgres:/
#docker exec -it postgres bash

##in container postgres.##
#su postgres
#createdb guacamole_db
#cat initdb.sql | psql -d guacamole_db -f -



######Verifying the Guacamole install####
#http://HOSTNAME:8080/guacamole/
#username:guacadmin
#password:guacadmin
