version: "3.7"

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:5.0.1
    networks:
      - net_cetcxl_app
    ports:
      - 6379:6379
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/production/redis:/data
    command: "redis-server --appendonly yes"
