apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-algorithm-execution-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dap-algorithm-execution-platform
  template:
    metadata:
      labels:
        app: dap-algorithm-execution-platform
    spec:
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "mysql"
        effect: "NoSchedule"
      nodeSelector:
        persistentData: "yes"
      imagePullSecrets:
      - name: docker
      containers:
      - name: dap-algorithm-execution-platform
        imagePullPolicy: Always
        image: docker.cetcxl.local/dap-algorithm-execution-platform:${IMAGE_TAG}
        env:
        - name: TZ
          value: "Asia/Shanghai"
        envFrom:
        - configMapRef:
            name: dap-algorithm-execution-platform
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /home/dap/algorithm
            name: data-excution
      volumes:
      - name: data-excution
        hostPath:
          path: /K8S_VOL/dap/execution

---
apiVersion: v1
kind: Service
metadata:
  name: dap-algorithm-execution-platform
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    #nodePort: 30001
  selector:
    app: dap-algorithm-execution-platform
    
