version: '3.7'

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7.29
    networks:
      - net_cetcxl_app
    ports:
      - 3306:3306
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    volumes:
      - /var/production/mysql:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
