apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlpay-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xlpay-admin
  template:
    metadata:
      labels:
        app: xlpay-admin
    spec:
      imagePullSecrets:
      - name: ${NAMESPACE}-ci-docker
      containers:
      - name: xlpay-admin
        imagePullPolicy: Always
        image: docker.cetcxl.local/xlpay-admin:${IMAGE_TAG}
        env:
        - name: TZ
          value: "Asia/Shanghai"
        envFrom:
        - configMapRef:
            name: xlpay-admin
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: xlpay-admin
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    #nodePort: 30001
  selector:
    app: xlpay-admin
    
