version: '3.8'


services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always
    ports:
    - "4822:4822"
    environment:
      TZ: Asia/Shanghai

  # postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      TZ: Asia/Shanghai
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres

  # guacamole
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      TZ: Asia/Shanghai
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    links:
      - "guacd"
      - "postgres"
    ports:
      - "8080:8080"
    restart: always
