version: "3.7"

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.4
    networks:
      - net_cetcxl_app
    ports:
      - 2181:2181
    restart: always
    environment:
      - TZ=Asia/Shanghai
