version: '3.7'

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    networks:
      - net_cetcxl_app
    ports:
      - 5672:5672
      - 8880:15672
    restart: always
    volumes:
      - /var/production/rabbitmq:/var/lib/rabbitmq
