version: "3.7"

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  elasticsearch1:
    image: 172.16.101.214:5000/elasticsearch
    container_name: elasticsearch1
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - net_cetcxl_app
      
  elasticsearch2:
    image: 172.16.101.214:5000/elasticsearch
    container_name: elasticsearch2
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - net_cetcxl_app
      
  elasticsearch3:
    image: 172.16.101.214:5000/elasticsearch
    container_name: elasticsearch3
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
      - 9303:9300
    networks:
      - net_cetcxl_app


  headPlugin:
    image: mobz/elasticsearch-head:5
    container_name: head
    restart: always
    ports:
      - 9100:9100
    networks:
      - net_cetcxl_app

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local