version: "3.7"

networks:
  net_cetcxl_app:
    external: true
    attachable: true
    driver: overlay

services:
  mysql-master-sys:
    container_name: mysql-master-sys
    image: mysql:5.7
    networks:
      - net_cetcxl_app
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    volumes:
      - /deploy/mysql-cluster/master-sys.cnf:/etc/mysql/conf.d/master.cnf
      - /var/production/mysql-master-sys:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  mysql-slave-notice:
    container_name: mysql-slave-notice
    image: mysql:5.7
    networks:
      - net_cetcxl_app
    ports:
      - 3308:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    volumes:
      - /deploy/mysql-cluster/slave-notice.cnf:/etc/mysql/conf.d/slave.cnf
      - /var/production/mysql-slave-notice:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  mysql-slave-ks:
    container_name: mysql-slave-ks
    image: mysql:5.7
    networks:
      - net_cetcxl_app
    ports:
      - 3309:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    volumes:
      - /deploy/mysql-cluster/slave-ks.cnf:/etc/mysql/conf.d/slave.cnf
      - /var/production/mysql-slave-ks:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"


  mysql-slave-score:
    container_name: mysql-slave-score
    image: mysql:5.7
    networks:
      - net_cetcxl_app
    ports:
      - 3310:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    volumes:
      - /deploy/mysql-cluster/slave-score.cnf:/etc/mysql/conf.d/slave.cnf
      - /var/production/mysql-slave-score:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
 
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - net_cetcxl_app
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - MYSQL_DATABASE=saga
      - MYSQL_PASSWORD=password
      - MYSQL_USER=saga
      - LANG=C.UTF-8
    volumes:
      - /var/production/mysql:/var/lib/mysql
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
