apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-operate-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dap-operate-platform
  template:
    metadata:
      labels:
        app: dap-operate-platform
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - name: dap-operate-platform
        imagePullPolicy: Always
        image: docker.cetcxl.local/dap-operate-platform:${IMAGE_TAG}
        env:
        - name: TZ
          value: "Asia/Shanghai"
        envFrom:
        - configMapRef:
            name: dap-operate-platform
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dap-operate-platform
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    #nodePort: 30001
  selector:
    app: dap-operate-platform
    
